services:
  backend:
    image: spaceresearch
    env_file:
      - ./vars.env
    networks:
      - spaceresearch_net
      - net
    ports:
      - "8080:8080"


  database:
    image: spaceresearch-postgres
    env_file:
      - ./vars.env
    networks:
      - spaceresearch_net
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data


  objectstorage:
    image: spaceresearch-objectstorage
    env_file:
      - ./vars.env
    networks:
      - spaceresearch_net
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data


  messagebroker:
    image: rabbitmq:management-alpine
    env_file:
      - ./vars.env
    networks:
      - spaceresearch_net
    ports:
      - "5672:5672"
      - "15672:15672"


networks:
  spaceresearch_net:
    external: false
  net:
    external: true
