services:
  backend:
    image: spaceresearch
    restart: unless-stopped
    env_file:
      - ./vars.env
    networks:
      - spaceresearch_net
      - net
    ports:
      - "8080:8080"


  database:
    image: spaceresearch-postgres
    restart: unless-stopped
    env_file:
      - ./vars.env
    networks:
      - spaceresearch_net
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data


  objectstorage:
    image: spaceresearch-objectstorage
    restart: unless-stopped
    env_file:
      - ./vars.env
    networks:
      - spaceresearch_net
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data


  messagebroker:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    env_file:
      - ./vars.env
    networks:
      - spaceresearch_net
    ports:
      - "5672:5672"
      - "15672:15672"


  documentprocessor:
    image: spaceresearch-documentprocessor
    restart: unless-stopped
    env_file:
      - ./vars.env
    networks:
      - spaceresearch_net


  # ollama:
  #   image: ollama/ollama
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"
  #   networks:
  #     - spaceresearch_net
  #   volumes:
  #     - ollama_data:/root/.ollama


networks:
  spaceresearch_net:
    external: false
  net:
    external: true
