// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.887
package signinForm

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SignInForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"col-md-8 col-lg-6\"><div class=\"card p-4\"><div class=\"text-center mb-4\"><h1 class=\"h3 fw-bold\">Welcome Back</h1><p class=\"text-muted\">Sign in to manage your team</p></div><form class=\"needs-validation\" action=\"/process-signin\" method=\"post\" novalidate><!-- Email Field --><div class=\"mb-3\"><label for=\"email\" class=\"form-label\">Email Address</label><div class=\"input-group\"><span class=\"input-group-text\"><i class=\"bi bi-envelope\"></i></span> <input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" placeholder=\"name@example.com\" required></div><div class=\"invalid-feedback\">Please provide a valid email address.</div></div><!-- Password Field --><div class=\"mb-4\"><label for=\"password\" class=\"form-label\">Password</label><div class=\"input-group\"><span class=\"input-group-text\"><i class=\"bi bi-lock\"></i></span> <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" placeholder=\"Your password\" required></div><div class=\"invalid-feedback\">Please enter your password.</div></div><!-- Submit Button --><button type=\"submit\" class=\"btn btn-primary w-100 py-2 mb-3\">Sign In <i class=\"bi bi-arrow-right-short\"></i></button><div class=\"text-center\"><a href=\"/signup\" class=\"text-decoration-none\">Don't have an account? Sign Up</a></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
